#!/bin/bash
# ╔════════════════════════════════════════════════╗
# │ Autor: Daniel Calderon - Kapelu                │
# │ Versión: 3.5                                   │
# │ Fecha: 12/01/2024 15:56:43                     │
# │ WebSite: https://danielcalderon.vercel.app/    │
# ╚════════════════════════════════════════════════╝

sudo apt update -y
sudo apt install --fix-missing -y -f 
sudo apt upgrade -y 
sudo apt full-upgrade -y 
sudo apt install -f 
sudo apt autoremove -y 
sudo apt autoclean 
sudo apt -y clean

