import './globals.css'
import Header from './component/Header.jsx'
import Footer from './component/Footer.jsx'

export const metadata = {
	title: 'Create React App',
	description: 'Generated by create next app',
}

export default function RootLayout({children}) {
	return (
		<html lang='es'>
			<body>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
