/* import {Inter} from 'next/font/google' */
import './style/global.css'
import Header from './component/Header'
import Sidebar from './component/Sidebar'

/* const inter = Inter({subsets: ['latin']}) */

export const metadata = {
	title: 'Create React App',
	description: 'Generated by create next app',
}

export default function RootLayout({children}) {
	return (
		<html lang='es'>
			<head>
				<meta charSet='UTF-8' />
			</head>
			<body>
				<div className='layout-container'>
					<Header />
					<div className='content-container'>
						<Sidebar />
						<main>{children}</main>
					</div>
				</div>
			</body>
		</html>
	)
}
