import './style/style.css'
import Header from './component/Header.jsx'
import Sidebar from './component/Sidebar.jsx'

export const metadata = {
	title: 'Create React App',
	description: 'Generated by create next app',
}

export default function RootLayout({children}) {
	return (
		<html lang='es'>
			<head>
				<meta charSet='UTF-8' />
			</head>
			<body>
				<div>
					<Header />
					
					<div>
						<Sidebar />
						<main>{children}</main>
					</div>
				</div>
				<script src="./component/index.js" type="module"></script>
			</body>
		</html>
	)
}
