'useClient'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'
import Navbar from './components/Navbar'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	keywords: 'Daniel Calderon developer, ReactJs, NextJs, tutorial, Bootstrap,MaterialUi',
}

export default function RootLayout({children}) {
	return (
		<html lang='es'>
			<head></head>
			<body suppressHydrationWarning={true}>
				<Header />
				<main className='main'>
					<Navbar />
					<section className='section'>{children}</section>
					<div style={{borderRight: '1px solid var(--first-color)'}}></div>
				</main>
				<Footer />
			</body>
		</html>
	)
}
