#!/bin/bash
# ╔════════════════════════════════════════════════╗
# │ Autor: Daniel Calderon - Kapelu                │
# │ Versión: 3.5                                   │
# │ Fecha: 12/01/2024 15:56:43                     │
# │ WebSite: https://danielcalderon.vercel.app/    │
# ╚════════════════════════════════════════════════╝

verde='\033[33m'
amarillo='\033[34m'
azul='\033[35m'
reset='\033[0m'


echo -e "$azul Repositorio a Clonar:$reset \c "
read repo
echo ''
git clone "$repo" --depth 1
echo ''
echo -e "$verde Repositorio creado con exito !!! $reset"
echo ''

